dist: trusty
sudo: false

language: node_js

node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9

env:
  - NODE_ENV=test WEBPACK_VERSION=1.x
  - NODE_ENV=test WEBPACK_VERSION=2.x
  - NODE_ENV=test WEBPACK_VERSION=3.x
  - NODE_ENV=test WEBPACK_VERSION=4.x

before_install:
  - npm install -g npm
install:
  - npm install
script:
  - scripts/test.sh

# webpack 4 supports only node 6+
matrix:
  exclude:
    - node_js: 4
      env: NODE_ENV=test WEBPACK_VERSION=4.x
    - node_js: 5
      env: NODE_ENV=test WEBPACK_VERSION=4.x
